name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Update on push to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: CroWzblooD
          template: classic
          base: "header"  # This shows only your name and avatar
          
          # Only isometric calendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
